#!/bin/sh

set -x

rm    ./src/Makevars
rm    ./src/*.o
rm    ./src/*.so
rm -r ./src/CMakeFiles
rm -r ./CMakeFiles

#rm    install-symengine.log
#rm -r ./symengine_dist

PKG_DIR=`pwd`

cd src/upstream
make clean

cd $PKG_DIR

rm -r src/upstream/CMakeFiles
rm    src/upstream/Makefile
rm    src/upstream/doc/Makefile
rm    src/upstream/symengine/Makefile
rm    src/upstream/symengine/utilities/matchpycpp/Makefile

