# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.basic_add <- function(exta, extb) {
    .Call('_symengine_sexp_basic_add', PACKAGE = 'symengine', exta, extb)
}

.basic_sub <- function(exta, extb) {
    .Call('_symengine_sexp_basic_sub', PACKAGE = 'symengine', exta, extb)
}

.basic_mul <- function(exta, extb) {
    .Call('_symengine_sexp_basic_mul', PACKAGE = 'symengine', exta, extb)
}

.basic_div <- function(exta, extb) {
    .Call('_symengine_sexp_basic_div', PACKAGE = 'symengine', exta, extb)
}

.basic_pow <- function(exta, extb) {
    .Call('_symengine_sexp_basic_pow', PACKAGE = 'symengine', exta, extb)
}

.basic_diff <- function(exta, extb) {
    .Call('_symengine_sexp_basic_diff', PACKAGE = 'symengine', exta, extb)
}

.basic_expand <- function(exta) {
    .Call('_symengine_sexp_basic_expand', PACKAGE = 'symengine', exta)
}

.basic_neg <- function(exta) {
    .Call('_symengine_sexp_basic_neg', PACKAGE = 'symengine', exta)
}

.basic_abs <- function(exta) {
    .Call('_symengine_sexp_basic_abs', PACKAGE = 'symengine', exta)
}

.basic_erf <- function(exta) {
    .Call('_symengine_sexp_basic_erf', PACKAGE = 'symengine', exta)
}

.basic_erfc <- function(exta) {
    .Call('_symengine_sexp_basic_erfc', PACKAGE = 'symengine', exta)
}

.basic_sin <- function(exta) {
    .Call('_symengine_sexp_basic_sin', PACKAGE = 'symengine', exta)
}

.basic_cos <- function(exta) {
    .Call('_symengine_sexp_basic_cos', PACKAGE = 'symengine', exta)
}

.basic_tan <- function(exta) {
    .Call('_symengine_sexp_basic_tan', PACKAGE = 'symengine', exta)
}

.basic_asin <- function(exta) {
    .Call('_symengine_sexp_basic_asin', PACKAGE = 'symengine', exta)
}

.basic_acos <- function(exta) {
    .Call('_symengine_sexp_basic_acos', PACKAGE = 'symengine', exta)
}

.basic_atan <- function(exta) {
    .Call('_symengine_sexp_basic_atan', PACKAGE = 'symengine', exta)
}

.basic_csc <- function(exta) {
    .Call('_symengine_sexp_basic_csc', PACKAGE = 'symengine', exta)
}

.basic_sec <- function(exta) {
    .Call('_symengine_sexp_basic_sec', PACKAGE = 'symengine', exta)
}

.basic_cot <- function(exta) {
    .Call('_symengine_sexp_basic_cot', PACKAGE = 'symengine', exta)
}

.basic_acsc <- function(exta) {
    .Call('_symengine_sexp_basic_acsc', PACKAGE = 'symengine', exta)
}

.basic_asec <- function(exta) {
    .Call('_symengine_sexp_basic_asec', PACKAGE = 'symengine', exta)
}

.basic_acot <- function(exta) {
    .Call('_symengine_sexp_basic_acot', PACKAGE = 'symengine', exta)
}

.basic_sinh <- function(exta) {
    .Call('_symengine_sexp_basic_sinh', PACKAGE = 'symengine', exta)
}

.basic_cosh <- function(exta) {
    .Call('_symengine_sexp_basic_cosh', PACKAGE = 'symengine', exta)
}

.basic_tanh <- function(exta) {
    .Call('_symengine_sexp_basic_tanh', PACKAGE = 'symengine', exta)
}

.basic_asinh <- function(exta) {
    .Call('_symengine_sexp_basic_asinh', PACKAGE = 'symengine', exta)
}

.basic_acosh <- function(exta) {
    .Call('_symengine_sexp_basic_acosh', PACKAGE = 'symengine', exta)
}

.basic_atanh <- function(exta) {
    .Call('_symengine_sexp_basic_atanh', PACKAGE = 'symengine', exta)
}

.basic_csch <- function(exta) {
    .Call('_symengine_sexp_basic_csch', PACKAGE = 'symengine', exta)
}

.basic_sech <- function(exta) {
    .Call('_symengine_sexp_basic_sech', PACKAGE = 'symengine', exta)
}

.basic_coth <- function(exta) {
    .Call('_symengine_sexp_basic_coth', PACKAGE = 'symengine', exta)
}

.basic_acsch <- function(exta) {
    .Call('_symengine_sexp_basic_acsch', PACKAGE = 'symengine', exta)
}

.basic_asech <- function(exta) {
    .Call('_symengine_sexp_basic_asech', PACKAGE = 'symengine', exta)
}

.basic_acoth <- function(exta) {
    .Call('_symengine_sexp_basic_acoth', PACKAGE = 'symengine', exta)
}

.basic_lambertw <- function(exta) {
    .Call('_symengine_sexp_basic_lambertw', PACKAGE = 'symengine', exta)
}

.basic_zeta <- function(exta) {
    .Call('_symengine_sexp_basic_zeta', PACKAGE = 'symengine', exta)
}

.basic_dirichlet_eta <- function(exta) {
    .Call('_symengine_sexp_basic_dirichlet_eta', PACKAGE = 'symengine', exta)
}

.basic_gamma <- function(exta) {
    .Call('_symengine_sexp_basic_gamma', PACKAGE = 'symengine', exta)
}

.basic_sqrt <- function(exta) {
    .Call('_symengine_sexp_basic_sqrt', PACKAGE = 'symengine', exta)
}

.basic_exp <- function(exta) {
    .Call('_symengine_sexp_basic_exp', PACKAGE = 'symengine', exta)
}

.basic_log <- function(exta) {
    .Call('_symengine_sexp_basic_log', PACKAGE = 'symengine', exta)
}

.basic_subs2 <- function(exte, exta, extb) {
    .Call('_symengine_sexp_basic_subs2', PACKAGE = 'symengine', exte, exta, extb)
}

.basic_evalf <- function(extb, bits, real) {
    .Call('_symengine_sexp_basic_evalf', PACKAGE = 'symengine', extb, bits, real)
}

.basic_type <- function(ext) {
    .Call('_symengine_sexp_basic_type', PACKAGE = 'symengine', ext)
}

.basic_str <- function(ext) {
    .Call('_symengine_sexp_basic_str', PACKAGE = 'symengine', ext)
}

.basic_hash <- function(ext) {
    .Call('_symengine_sexp_basic_hash', PACKAGE = 'symengine', ext)
}

.basic_eq <- function(exta, extb) {
    .Call('_symengine_sexp_basic_eq', PACKAGE = 'symengine', exta, extb)
}

.basic_neq <- function(exta, extb) {
    .Call('_symengine_sexp_basic_neq', PACKAGE = 'symengine', exta, extb)
}

.basic_symbol <- function(RString) {
    .Call('_symengine_sexp_basic_symbol', PACKAGE = 'symengine', RString)
}

.basic_parse <- function(RString) {
    .Call('_symengine_sexp_basic_parse', PACKAGE = 'symengine', RString)
}

.basic_const <- function(string) {
    .Call('_symengine_sexp_basic_const', PACKAGE = 'symengine', string)
}

.basic_const_zero <- function() {
    .Call('_symengine_sexp_const_zero', PACKAGE = 'symengine')
}

.basic_const_one <- function() {
    .Call('_symengine_sexp_const_one', PACKAGE = 'symengine')
}

.basic_const_minus_one <- function() {
    .Call('_symengine_sexp_const_minus_one', PACKAGE = 'symengine')
}

.basic_const_I <- function() {
    .Call('_symengine_sexp_const_I', PACKAGE = 'symengine')
}

.basic_const_pi <- function() {
    .Call('_symengine_sexp_const_pi', PACKAGE = 'symengine')
}

.basic_const_E <- function() {
    .Call('_symengine_sexp_const_E', PACKAGE = 'symengine')
}

.basic_const_EulerGamma <- function() {
    .Call('_symengine_sexp_const_EulerGamma', PACKAGE = 'symengine')
}

.basic_const_Catalan <- function() {
    .Call('_symengine_sexp_const_Catalan', PACKAGE = 'symengine')
}

.basic_const_GoldenRatio <- function() {
    .Call('_symengine_sexp_const_GoldenRatio', PACKAGE = 'symengine')
}

.basic_const_infinity <- function() {
    .Call('_symengine_sexp_const_infinity', PACKAGE = 'symengine')
}

.basic_const_neginfinity <- function() {
    .Call('_symengine_sexp_const_neginfinity', PACKAGE = 'symengine')
}

.basic_const_complex_infinity <- function() {
    .Call('_symengine_sexp_const_complex_infinity', PACKAGE = 'symengine')
}

.basic_const_nan <- function() {
    .Call('_symengine_sexp_const_nan', PACKAGE = 'symengine')
}

.basic_integer_fromint <- function(x) {
    .Call('_symengine_sexp_basic_integer_fromint', PACKAGE = 'symengine', x)
}

.basic_integer_fromstr <- function(RString) {
    .Call('_symengine_sexp_basic_integer_fromstr', PACKAGE = 'symengine', RString)
}

.basic_integer_getint <- function(ext) {
    .Call('_symengine_sexp_basic_integer_getint', PACKAGE = 'symengine', ext)
}

.basic_realdouble <- function(x) {
    .Call('_symengine_sexp_basic_realdouble', PACKAGE = 'symengine', x)
}

.basic_realdouble_getd <- function(ext) {
    .Call('_symengine_sexp_basic_realdouble_getd', PACKAGE = 'symengine', ext)
}

.basic_isNumber <- function(ext) {
    .Call('_symengine_sexp_basic_isNumber', PACKAGE = 'symengine', ext)
}

.basic_isInteger <- function(ext) {
    .Call('_symengine_sexp_basic_isInteger', PACKAGE = 'symengine', ext)
}

.basic_isRational <- function(ext) {
    .Call('_symengine_sexp_basic_isRational', PACKAGE = 'symengine', ext)
}

.basic_isSymbol <- function(ext) {
    .Call('_symengine_sexp_basic_isSymbol', PACKAGE = 'symengine', ext)
}

.basic_isComplex <- function(ext) {
    .Call('_symengine_sexp_basic_isComplex', PACKAGE = 'symengine', ext)
}

.basic_isRealDouble <- function(ext) {
    .Call('_symengine_sexp_basic_isRealDouble', PACKAGE = 'symengine', ext)
}

.basic_isComplexDouble <- function(ext) {
    .Call('_symengine_sexp_basic_isComplexDouble', PACKAGE = 'symengine', ext)
}

.basic_isRealMPFR <- function(ext) {
    .Call('_symengine_sexp_basic_isRealMPFR', PACKAGE = 'symengine', ext)
}

.basic_isComplexMPC <- function(ext) {
    .Call('_symengine_sexp_basic_isComplexMPC', PACKAGE = 'symengine', ext)
}

.basic_num_iszero <- function(ext) {
    .Call('_symengine_sexp_basic_num_iszero', PACKAGE = 'symengine', ext)
}

.basic_num_isnegative <- function(ext) {
    .Call('_symengine_sexp_basic_num_isnegative', PACKAGE = 'symengine', ext)
}

.basic_num_ispositive <- function(ext) {
    .Call('_symengine_sexp_basic_num_ispositive', PACKAGE = 'symengine', ext)
}

.basic_num_iscomplex <- function(ext) {
    .Call('_symengine_sexp_basic_num_iscomplex', PACKAGE = 'symengine', ext)
}

.symengine_ascii_art <- function() {
    .Call('_symengine_sexp_symengine_ascii_art', PACKAGE = 'symengine')
}

symengine_version <- function() {
    .Call('_symengine_sexp_symengine_version', PACKAGE = 'symengine')
}

.symengine_have_component <- function(s) {
    .Call('_symengine_sexp_symengine_have_component', PACKAGE = 'symengine', s)
}

.vecbasic_new <- function() {
    .Call('_symengine_sexp_vecbasic_new', PACKAGE = 'symengine')
}

.vecbasic_push_back <- function(ext, value) {
    invisible(.Call('_symengine_sexp_vecbasic_push_back', PACKAGE = 'symengine', ext, value))
}

.vecbasic_get <- function(ext, n, val) {
    invisible(.Call('_symengine_sexp_vecbasic_get', PACKAGE = 'symengine', ext, n, val))
}

.vecbasic_size <- function(ext) {
    .Call('_symengine_sexp_vecbasic_size', PACKAGE = 'symengine', ext)
}

.vecbasic_set <- function(ext, n, val) {
    invisible(.Call('_symengine_sexp_vecbasic_set', PACKAGE = 'symengine', ext, n, val))
}

.vecbasic_erase <- function(ext, n) {
    invisible(.Call('_symengine_sexp_vecbasic_erase', PACKAGE = 'symengine', ext, n))
}

.basic_max <- function(val, ext) {
    invisible(.Call('_symengine_sexp_basic_max', PACKAGE = 'symengine', val, ext))
}

.basic_min <- function(val, ext) {
    invisible(.Call('_symengine_sexp_basic_min', PACKAGE = 'symengine', val, ext))
}

.vecbasic_concentrate <- function(dots) {
    .Call('_symengine_vecbasic_concentrate', PACKAGE = 'symengine', dots)
}

.vecbasic_get <- function(ext, n) {
    .Call('_symengine_vecbasic_get', PACKAGE = 'symengine', ext, n)
}

.vecbasic_subset <- function(ext, dots) {
    .Call('_symengine_vecbasic_subset', PACKAGE = 'symengine', ext, dots)
}

